package com.changeyourlife.cyl.presentation.theme

import androidx.compose.ui.graphics.Color

val CylPrimary = Color(0xFF171717)
val CylOnPrimary = Color(0xFFFAFAF7)
val CylPrimaryContainer = Color(0xFFE6E6E2)
val CylOnPrimaryContainer = Color(0xFF171717)
val CylSecondary = Color(0xFF4F4F4A)
val CylOnSecondary = Color(0xFFFAFAF7)
val CylSecondaryContainer = Color(0xFFEDEDEA)
val CylOnSecondaryContainer = Color(0xFF20201D)
val CylTertiary = Color(0xFF64635E)
val CylOnTertiary = Color(0xFFFAFAF7)
val CylTertiaryContainer = Color(0xFFE4E3DF)
val CylOnTertiaryContainer = Color(0xFF22221F)
val CylBackground = Color(0xFFF8F8F5)
val CylSurface = Color(0xFFFCFCFA)
val CylSurfaceVariant = Color(0xFFE8E8E4)
val CylSurfaceContainerLowest = Color(0xFFFFFFFF)
val CylSurfaceContainerLow = Color(0xFFF7F7F4)
val CylSurfaceContainer = Color(0xFFF0F0EC)
val CylSurfaceContainerHigh = Color(0xFFE7E7E2)
val CylSurfaceContainerHighest = Color(0xFFDCDCD6)
val CylOnSurface = Color(0xFF171717)
val CylOnSurfaceVariant = Color(0xFF5F5F59)
val CylOutline = Color(0xFF777771)
val CylOutlineVariant = Color(0xFFD9D9D3)
val CylInverseSurface = Color(0xFF2C2C29)
val CylInverseOnSurface = Color(0xFFF5F5F1)

val CylDarkPrimary = Color(0xFFF0F0EC)
val CylDarkOnPrimary = Color(0xFF171717)
val CylDarkPrimaryContainer = Color(0xFF30302D)
val CylDarkOnPrimaryContainer = Color(0xFFF0F0EC)
val CylDarkSecondary = Color(0xFFC9C9C3)
val CylDarkOnSecondary = Color(0xFF1F1F1D)
val CylDarkSecondaryContainer = Color(0xFF353531)
val CylDarkOnSecondaryContainer = Color(0xFFEAEAE5)
val CylDarkTertiary = Color(0xFFD6D5CF)
val CylDarkOnTertiary = Color(0xFF22221F)
val CylDarkTertiaryContainer = Color(0xFF3A3935)
val CylDarkOnTertiaryContainer = Color(0xFFF0F0EC)
val CylDarkBackground = Color(0xFF111111)
val CylDarkSurface = Color(0xFF171717)
val CylDarkSurfaceVariant = Color(0xFF3D3D39)
val CylDarkSurfaceContainerLowest = Color(0xFF0C0C0C)
val CylDarkSurfaceContainerLow = Color(0xFF1C1C1A)
val CylDarkSurfaceContainer = Color(0xFF242421)
val CylDarkSurfaceContainerHigh = Color(0xFF30302C)
val CylDarkSurfaceContainerHighest = Color(0xFF3A3A36)
val CylDarkOnSurface = Color(0xFFE8E8E3)
val CylDarkOnSurfaceVariant = Color(0xFFC6C6BF)
val CylDarkOutline = Color(0xFF91918A)
val CylDarkOutlineVariant = Color(0xFF454541)
val CylDarkInverseSurface = Color(0xFFE8E8E3)
val CylDarkInverseOnSurface = Color(0xFF1C1C1A)
