package com.changeyourlife.cyl.presentation.ai

import com.changeyourlife.cyl.aicontract.AiActionWire
import com.changeyourlife.cyl.aicontract.AiTableColumnWire
import com.changeyourlife.cyl.domain.repository.ChatAction

internal fun ChatAction.toContractWire(): AiActionWire = AiActionWire(
    type = type,
    title = title,
    targetTitle = targetTitle,
    content = content,
    blockType = blockType,
    blockId = blockId,
    blockText = blockText,
    textToFormat = textToFormat,
    format = format,
    linkUrl = linkUrl,
    color = color,
    highlight = highlight,
    rangeStart = rangeStart,
    rangeEnd = rangeEnd,
    mediaUri = mediaUri,
    mediaName = mediaName,
    mediaMimeType = mediaMimeType,
    mediaSizeBytes = mediaSizeBytes,
    isChecked = isChecked,
    propertyName = propertyName,
    propertyType = propertyType,
    value = value,
    moduleType = moduleType,
    tableTitle = tableTitle,
    tableView = tableView,
    calendarDateColumnId = calendarDateColumnId,
    calendarDateColumnName = calendarDateColumnName,
    timelineStartColumnId = timelineStartColumnId,
    timelineStartColumnName = timelineStartColumnName,
    timelineEndColumnId = timelineEndColumnId,
    timelineEndColumnName = timelineEndColumnName,
    dashboardMetricColumnId = dashboardMetricColumnId,
    dashboardMetricColumnName = dashboardMetricColumnName,
    dashboardGroupColumnId = dashboardGroupColumnId,
    dashboardGroupColumnName = dashboardGroupColumnName,
    columnId = columnId,
    columnName = columnName,
    newColumnName = newColumnName,
    columnType = columnType,
    options = options,
    formula = formula,
    relationTargetTableId = relationTargetTableId,
    relationTargetTableTitle = relationTargetTableTitle,
    rollupRelationColumnId = rollupRelationColumnId,
    rollupRelationColumnName = rollupRelationColumnName,
    rollupTargetColumnId = rollupTargetColumnId,
    rollupTargetColumnName = rollupTargetColumnName,
    rollupAggregation = rollupAggregation,
    sortDirection = sortDirection,
    filterQuery = filterQuery,
    groupByColumnId = groupByColumnId,
    groupByColumnName = groupByColumnName,
    rowId = rowId,
    rowTitle = rowTitle,
    newRowTitle = newRowTitle,
    rowBlockId = rowBlockId,
    targetIndex = targetIndex,
    cellValues = cellValues,
    tableColumns = tableColumns.map { column ->
        AiTableColumnWire(
            name = column.name,
            type = column.type,
            options = column.options,
            dateFormat = column.dateFormat,
            timeFormat = column.timeFormat,
            dateReminder = column.dateReminder,
            timezoneLabel = column.timezoneLabel,
            formula = column.formula,
            relationTargetTableId = column.relationTargetTableId,
            rollupRelationColumnName = column.rollupRelationColumnName,
            rollupTargetColumnName = column.rollupTargetColumnName,
            rollupAggregation = column.rollupAggregation,
        )
    },
    tableRows = tableRows,
    delayMinutes = delayMinutes,
)
